---

- name: Check if openshift-compliance namespace exists
  shell: oc get ns openshift-compliance
  register: ns_results
  failed_when: ns_results.rc == 2

- name: Create openshift-compliance namespace
  shell: oc create ns openshift-compliance
  when: ns_results.rc == 1

- name: Create operator-group.yaml
  file:
    path: '{{ work_dir }}/operator-group.yaml'
    state: touch

- name: Create operator group
  blockinfile:
    path: '{{ work_dir }}/operator-group.yaml' 
    block: | 
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: compliance-operator
        namespace: openshift-compliance
      spec:
        targetNamespaces:
        - openshift-compliance

- name: Create subscription.yaml
  file: 
    path: '{{ work_dir }}/subscription.yaml'
    state: touch

- name: Create subscription 
  blockinfile:
    path: '{{ work_dir }}/subscription.yaml'
    block: |
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: compliance-operator-sub
        namespace: openshift-compliance
      spec:
        channel: alpha
        name: compliance-operator
        source: {{ catalog_source }}
        sourceNamespace: openshift-marketplace
        # uncomment to specify a version
        #startingCSV: compliance-operator.v0.1.15
      




