---

- name: Create scansettingbinding custom resource file
  file:
    path: '{{ work_dir }}/compliance.openshift.io/v1alpha1_scansettingbinding_cr.yaml'
    state: touch

- name: Add content to scansettingbinding custom resource
  blockinfile:
    path: '{{ work_dir }}/compliance.openshift.io/v1alpha1_scansettingbinding_cr.yaml'
    block: |
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ScanSettingBinding
      metadata:
        name: {{ scan_name }}
      profiles:
        - name: {{ scan_profile }}
          kind: Profile
          apiGroup: compliance.openshift.io/v1alpha1
      settingsRef:
        name: default
        kind: ScanSetting
        apiGroup: compliance.openshift.io/v1alpha1

- name: Start a scan by creating the scansettingbinding custom resource object
  shell: oc create -n {{ namespace }} -f '{{ work_dir }}/compliance.openshift.io/v1alpha1_scansettingbinding_cr.yaml'

- name: Retrieve master scan results from PVC
  shell: oc get pvc | grep master | awk '{print $3}'
  register: master_results

- name: Create pod file that mounts the PV for master scan results
  blockinfile:
    path: '{{ work_dir }}/master-pv-extract.yml'
    block: |
      apiVersion: "v1"
      kind: Pod
      metadata:
        name: master-pv-extract
      spec:
        containers:
        - name: master-pv-extract
          image: registry.access.redhat.com/ubi8/ubi
          command: ["sleep", "3000"]
          volumeMounts:
            - mountPath: "/masters-scan-results"
              name: masters-scan-vol
        volumes:
        - name: masters-scan-vol
          persistentVolumeClaim:
            claimName: '{{ master_results }}'

- name: Start master-pv-extract pod
  shell: oc create -n {{ namespace }} -f '{{ work_dir }}/master-pv-extract.yml'

- name: Create directory to hold master scan results
  file:
    path: '{{ work_dir }}/masters-scan-results'
    state: directory

- name: Copy results directory from master-pv-extract pod 
  shell: oc cp master-pv-extract:/masters-scan-results '{{ work_dir }}/masters-scan-results/'

- name: Retrieve worker scan results from PVC
  shell: oc get pvc | grep worker | awk '{print $3}'
  register: worker_results

- name: Create pod file that mounts the PV for worker scan results
  blockinfile:
    path: '{{ work_dir }}/worker-pv-extract.yml'
    block: |
      apiVersion: "v1"
      kind: Pod
      metadata:
        name: worker-pv-extract
      spec:
        containers:
        - name: master-pv-extract
          image: registry.access.redhat.com/ubi8/ubi
          command: ["sleep", "3000"]
          volumeMounts:
            - mountPath: "/workers-scan-results"
              name: workers-scan-vol
        volumes:
        - name: workers-scan-vol
          persistentVolumeClaim:
            claimName: '{{ worker_results }}'

- name: Start worker-pv-extract pod
  shell: oc create -n {{ namespace }} -f '{{ work_dir }}/worker-pv-extract.yml'

- name: Create directory to hold worker scan results
  file:
    path: '{{ work_dir }}/workers-scan-results'
    state: directory

- name: Copy results directory from master-pv-extract pod
  shell: oc cp master-pv-extract:/workers-scan-results '{{ work_dir }}/workers-scan-results/'



