---

- name: Create operator-group.yaml
  file:
    path: '{{ work_dir }}/operator-group.yaml'
    state: touch

- name: Add operator group definition 
  blockinfile:
    path: '{{ work_dir }}/operator-group.yaml' 
    block: | 
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: compliance-operator
        namespace: '{{ namespace }}'
      spec:
        targetNamespaces:
        - '{{ namespace }}'

- name: Create the operator group
  shell: oc create -f '{{ work_dir }}/operator-group.yaml'
  ignore_errors: yes

- name: Create subscription.yaml
  file: 
    path: '{{ work_dir }}/subscription.yaml'
    state: touch

- name: Add subscription definition
  blockinfile:
    path: '{{ work_dir }}/subscription.yaml'
    block: |
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: compliance-operator-sub
        namespace: '{{ namespace }}'
      spec:
        channel: alpha
        name: compliance-operator
        source: {{ catalog_source }}
        sourceNamespace: openshift-marketplace
        # uncomment to specify a version
        startingCSV: '{{ version }}' 
      
- name: Create the subscription
  shell: oc create -f '{{ work_dir }}/subscription.yaml'
  ignore_errors: yes


