---

- name: Create operator-group.yaml
  file:
    path: '{{ work_dir }}/operator-group.yaml'
    state: touch

- name: Add operator group definition 
  blockinfile:
    path: '{{ work_dir }}/operator-group.yaml' 
    block: | 
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: compliance-operator
        namespace: openshift-compliance
      spec:
        targetNamespaces:
        - openshift-compliance

- name: Create the operator group
  shell: oc create -f '{{ work_dir }}/operator-group.yml'

- name: Create subscription.yaml
  file: 
    path: '{{ work_dir }}/subscription.yaml'
    state: touch

- name: Add subscription definition
  blockinfile:
    path: '{{ work_dir }}/subscription.yaml'
    block: |
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: compliance-operator-sub
        namespace: openshift-compliance
      spec:
        channel: alpha
        name: compliance-operator
        source: {{ catalog_source }}
        sourceNamespace: openshift-marketplace
        # uncomment to specify a version
        #startingCSV: compliance-operator.v0.1.15
      
- name: Create the subscription
  shell: oc create -f '{{ work_dir }}/subscription.yml'



