---

- name: Create operator group 
  k8s:
    state: present
    definition: 
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: compliance-operator
        namespace: '{{ namespace }}'
      spec:
        targetNamespaces:
        - '{{ namespace }}'


- name: Create subscription for compliance operator 
  k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: compliance-operator-sub
        namespace: '{{ namespace }}'
      spec:
        channel: release-0.1
        installPlanApproval: Automatic
        name: compliance-operator
        source: '{{ catalog_source }}'
        sourceNamespace: openshift-marketplace
        # uncomment to specify a version
        #startingCSV: '{{ version }}' 
      


