---

- name: Create the openshift-compliance namespace
  k8s:
    apply: yes
    definition:
      api_version: v1
      kind: Namespace
      name: openshift-compliance

- name: Create openscap directory
  file:
    path: '{{ work_dir }}'
    state: directory

- import_tasks: install_operator.yml
  when: install_operator | bool 

- import_tasks: scan.yml
  when: scan | bool

- import_tasks: results.yml
  when: results | bool
