---

- name: Log into cluster
  shell: 'oc login -u {{ user }} -p {{ password }} {{ cluster_url }}'

- name: Check to see if there is openshift-compliance namespace
  shell: oc project openshift-compliance 
  register: compliance_ns
  failed_when: compliance_ns.rc == 2

- name: Create openscap directory
  file:
    path: '{{ work_dir }}'
    state: directory

- name: Create openshift-compliance namespace
  shell: oc new-project openshift-compliance
  when: compliance_ns.rc == 1

- import_tasks: catalog.yml
  when: catalog | bool 

- import_tasks: source.yml
  when: source | bool 

- import_tasks: scan.yml
  when: scan | bool


