---

- name: Check to see if there is an openshift-compliance namespace
  shell: 'oc create ns {{ namespace }}' 
  register: compliance_ns
  failed_when: compliance_ns.rc == 2

- name: Create openshift-compliance namespace
  shell: 'oc create ns {{ namespace }}'
  register: create_ns
  when: compliance_ns.rc == 1
  failed_when: create_ns.rc == 2

- name: Create openscap directory
  file:
    path: '{{ work_dir }}'
    state: directory

- import_tasks: catalog.yml
  when: catalog | bool 

- import_tasks: source.yml
  when: source | bool 

- import_tasks: scan.yml
  when: scan | bool

- import_tasks: results.yml
  when: results | bool
