---

- name: Check if the scansetting already exists
  shell: oc get scansetting -n '{{ namespace }}' | grep '{{ scan_setting }}'
  register: scansetting
  failed_when: scansetting.rc == 2

- name: Create a file for a ScanSetting resource
  file:
    path: '{{ work_dir }}/{{ scan_setting }}_scansetting_cr.yaml'
    state: touch
  when: scansetting.rc == 1

- name: Define the scansetting
  blockinfile:
    path: '{{ work_dir }}/{{ scan_setting }}_scansetting_cr.yaml'
    block: |
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ScanSetting
      metadata:
        name: '{{ scan_setting }}'
        namespace: '{{ namespace }}'
      rawResultStorage:
        rotation: 3
        size: 1Gi
      roles:
      - worker
      - master
      scanTolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        Key: node-role.kubernetes.io/infra
        operator: Exists      
      schedule: '{{ cron_schedule }}'
  when: scansetting.rc == 1
  
- name: Create the scansetting custom resource object
  shell: oc create -n '{{ namespace }}' -f '{{ work_dir }}/{{ scan_setting }}_scansetting_cr.yaml'
  register: scansetting
  failed_when: '"does not exist" in scansetting.stdout'


- name: Check if the scansettingbinding already exists
  shell: oc get scansettingbinding -n '{{ namespace }}' | grep '{{ scan_name }}'
  register: scansettingbinding
  failed_when: scansettingbinding.rc == 2
  
- name: Delete scansettingbinding if it exists
  shell: 'oc delete scansettingbinding/{{ scan_name }}'
  when: scansettingbinding.rc == 0
  
- name: Create scansettingbinding custom resource file
  file:
    path: '{{ work_dir }}/{{ scan_name }}_scansettingbinding_cr.yaml'
    state: touch

- name: Add content to scansettingbinding custom resource
  blockinfile:
    path: '{{ work_dir }}/{{ scan_name }}_scansettingbinding_cr.yaml'
    block: |
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ScanSettingBinding
      metadata:
        name: '{{ scan_name }}'
      profiles:
        - name: '{{ scan_profile }}'
          kind: Profile
          apiGroup: compliance.openshift.io/v1alpha1
      settingsRef:
        name: '{{ scan_setting }}'
        kind: ScanSetting
        apiGroup: compliance.openshift.io/v1alpha1
  
- name: Wait for scan pods to terminate before creating a new scansettingbinding
  pause:
    minutes: 1
  
- name: Start a scan by creating the scansettingbinding custom resource object
  shell: oc create -n '{{ namespace }}' -f '{{ work_dir }}/{{ scan_name }}_scansettingbinding_cr.yaml'
  register: binding
  failed_when: '"does not exist" in binding.stdout'
