---

- name: Define the ScanSetting
  k8s:
    apply: yes
    definition:
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ScanSetting
      metadata:
        name: '{{ scan_setting }}'
        namespace: '{{ namespace }}'
      rawResultStorage:
        rotation: 3
        size: 1Gi
      roles:
      - worker
      - master
      scanTolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      schedule: '{{ cron_schedule }}'
  
- name: Remove any existing ScanSettingBinding objects
  k8s:
    state: absent
    api_version: compliance.openshift.io/v1alpha1
    kind: ScanSettingBinding
    namespace: openshift-compliance

- name: Create the ScanSettingBinding custom resource
  k8s:
    state: present
    definition:
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ScanSettingBinding
      metadata:
        name: '{{ scan_name }}'
      profiles:
        - name: '{{ node_scan_profile }}'
          kind: Profile
          apiGroup: compliance.openshift.io/v1alpha1
        - name: '{{ platform_scan_profile }}'
          kind: Profile
          apiGroup: compliance.openshift.io/v1alpha1
      settingsRef:
        name: '{{ scan_setting }}'
        kind: ScanSetting
        apiGroup: compliance.openshift.io/v1alpha1
  

  

