---

- name: Clone git repository
  git:
    repo: '{{ git_url }}'
    dest: '{{ work_dir }}/compliance-operator'
    clone: yes

- name: Create custom resource definitions
  shell: 'for f in $(ls -1 {{ work_dir }}/compliance-operator/deploy/crds/*crd.yaml); do oc apply -f $f -n {{ namespace }}; done'

- name: Create remaining objects
  shell: 'oc apply -n {{ namespace }}  -f {{ work_dir }}/compliance-operator/deploy/'


